# Generated by Django 5.1.7 on 2025-03-17 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=20, unique=True)),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('barangay', models.CharField(max_length=100)),
                ('purok', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('respondent', models.CharField(max_length=100)),
                ('philhealth_member', models.BooleanField()),
                ('philhealth_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
