# Generated by Django 5.1.7 on 2025-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
    ]
